STICKERS = [
    "AK-47 | Legion of Anubis (Minimal Wear)",
    "AWP | Atheris (Minimal Wear)",
    "Souvenir Charm | Austin 2025 Highlight | I'm Right Behind You",
    "Souvenir Charm | Austin 2025 Highlight | Jimpphat Quadra Kill",
    "Souvenir Charm | Austin 2025 Highlight | Spinx Quadra Kill",
    "Charm | Baby's AK",
    "Charm | Big Kev",
    "Charm | Chicken Lil'",
    "Charm | Hot Sauce",
    "Charm | Lil' Ava",
    "Charm | Lil' Cap Gun",
    "Charm | Lil' Crass",
    "Charm | Pinch O' Salt",
    "Charm | Pocket AWP",
    "Charm | Stitch-Loaded",
    "Charm | That's Bananas",
    "Desert Eagle | Tilted (Minimal Wear)",
    "Sticker | 3DMAX (Foil) | Austin 2025",
    "Sticker | 3DMAX (Glitter) | Shanghai 2024",
    "Sticker | 3DMAX | Austin 2025",
    "Sticker | 910 (Foil) | Austin 2025",
    "Sticker | 910 (Glitter) | Copenhagen 2024",
    "Sticker | 910 (Holo) | Copenhagen 2024",
    "Sticker | 9INE (Glitter) | Paris 2023",
    "Sticker | AMKAL ESPORTS (Glitter) | Copenhagen 2024",
    "Sticker | ANNIHILATION (Glitter) | Paris 2023",
    "Sticker | ANNIHILATION (Holo) | Paris 2023",
    "Sticker | Aleksib (Glitter) | Copenhagen 2024",
    "Sticker | Apeks (Glitter) | Copenhagen 2024",
    "Sticker | Aurora (Foil) | Austin 2025",
    "Sticker | Aurora | Austin 2025",
    "Sticker | Ax1Le (Glitter) | Antwerp 2022",
    "Sticker | B8 (Foil) | Austin 2025",
    "Sticker | B8 | Austin 2025",
    "Sticker | BLAST.tv (Foil) | Austin 2025",
    "Sticker | BOROS (Glitter) | Paris 2023",
    "Sticker | Bad News Eagles (Glitter) | Antwerp 2022",
    "Sticker | Bad News Eagles | Antwerp 2022",
    "Sticker | BetBoom (Foil) | Austin 2025",
    "Sticker | BetBoom | Austin 2025",
    "Sticker | bodyy (Holo) | Austin 2025",
    "Sticker | Brollan (Glitter) | Antwerp 2022",
    "Sticker | Brollan (Glitter) | Copenhagen 2024",
    "Sticker | Brollan (Glitter) | Rio 2022",
    "Sticker | Brollan (Holo) | Austin 2025",
    "Sticker | CRUC1AL (Glitter) | Paris 2023",
    "Sticker | CacaNito (Glitter) | Copenhagen 2024",
    "Sticker | Chinggis Warriors (Foil) | Austin 2025",
    "Sticker | Chinggis Warriors | Austin 2025",
    "Sticker | Cloud9 (Glitter) | Copenhagen 2024",
    "Sticker | Complexity Gaming (Foil) | Austin 2025",
    "Sticker | Complexity Gaming (Glitter) | Copenhagen 2024",
    "Sticker | Complexity Gaming | Copenhagen 2024",
    "Sticker | Copenhagen Flames | Antwerp 2022",
    "Sticker | DemQQ (Glitter) | Paris 2023",
    "Sticker | device | Stockholm 2021",
    "Sticker | ECSTATIC (Glitter) | Copenhagen 2024",
    "Sticker | ENCE (Glitter) | Copenhagen 2024",
    "Sticker | EliGE (Glitter) | Copenhagen 2024",
    "Sticker | EliGE (Glitter) | Paris 2023",
    "Sticker | EliGE | Austin 2025",
    "Sticker | EmiliaQAQ (Glitter) | Copenhagen 2024",
    "Sticker | EmiliaQAQ | Copenhagen 2024",
    "Sticker | Ex3rcice (Holo) | Austin 2025",
    "Sticker | F1KU | Austin 2025",
    "Sticker | FL1T (Glitter) | Copenhagen 2024",
    "Sticker | FL1T (Glitter) | Rio 2022",
    "Sticker | FL1T (Holo, Champion) | Rio 2022",
    "Sticker | FURIA (Foil) | Austin 2025",
    "Sticker | FURIA (Glitter) | Antwerp 2022",
    "Sticker | FURIA (Glitter) | Copenhagen 2024",
    "Sticker | FURIA (Glitter) | Rio 2022",
    "Sticker | FURIA | Austin 2025",
    "Sticker | FURIA | Berlin 2019",
    "Sticker | FURIA | Copenhagen 2024",
    "Sticker | FaZe Clan (Foil) | Austin 2025",
    "Sticker | Falcons | Austin 2025",
    "Sticker | FlameZ (Glitter) | Copenhagen 2024",
    "Sticker | FlameZ (Glitter) | Rio 2022",
    "Sticker | Fluxo (Foil) | Austin 2025",
    "Sticker | Fluxo | Austin 2025",
    "Sticker | FlyQuest (Foil) | Austin 2025",
    "Sticker | FlyQuest | Austin 2025",
    "Sticker | G2 Esports (Foil) | Austin 2025",
    "Sticker | G2 Esports | Austin 2025",
    "Sticker | GeT_RiGhT | Berlin 2019",
    "Sticker | GODSENT | 2020 RMR",
    "Sticker | GamerLegion (Glitter) | Copenhagen 2024",
    "Sticker | GamerLegion | Copenhagen 2024",
    "Sticker | Goofy (Glitter) | Copenhagen 2024",
    "Sticker | Goofy (Glitter) | Paris 2023",
    "Sticker | Goofy (Holo) | Paris 2023",
    "Sticker | Goofy | Copenhagen 2024",
    "Sticker | Graviti (Glitter) | Shanghai 2024",
    "Sticker | Grayhound Gaming (Glitter) | Paris 2023",
    "Sticker | Grim (Foil) | Austin 2025",
    "Sticker | Grim (Glitter) | Copenhagen 2024",
    "Sticker | Grim (Glitter) | Shanghai 2024",
    "Sticker | Heavygod (Foil) | Austin 2025",
    "Sticker | Heavygod (Glitter) | Shanghai 2024",
    "Sticker | Heavygod (Gold) | Austin 2025",
    "Sticker | Heavygod (Holo) | Austin 2025",
    "Sticker | HEROIC (Foil) | Austin 2025",
    "Sticker | Heroic (Glitter) | Copenhagen 2024",
    "Sticker | HEROIC | Austin 2025",
    "Sticker | Hobbit (Glitter) | Antwerp 2022",
    "Sticker | HooXi (Glitter) | Copenhagen 2024",
    "Sticker | IEM (Glitter) | Rio 2022",
    "Sticker | IHC Esports (Glitter) | Antwerp 2022",
    "Sticker | IHC Esports (Glitter) | Rio 2022",
    "Sticker | IHC Esports | Antwerp 2022",
    "Sticker | INS (Glitter) | Paris 2023",
    "Sticker | ICY (Foil) | Austin 2025",
    "Sticker | ICY (Glitter) | Copenhagen 2024",
    "Sticker | ICY (Holo) | Copenhagen 2024",
    "Sticker | Imperial Esports (Foil) | Austin 2025",
    "Sticker | Imperial Esports (Glitter) | Copenhagen 2024",
    "Sticker | Imperial Esports | Austin 2025",
    "Sticker | Into The Breach (Glitter) | Paris 2023",
    "Sticker | JBa | Shanghai 2024",
    "Sticker | Jame (Glitter) | Copenhagen 2024",
    "Sticker | Jame (Glitter, Champion) | Rio 2022",
    "Sticker | Jame | Antwerp 2022",
    "Sticker | Jerry (Glitter) | Antwerp 2022",
    "Sticker | Jerry (Glitter) | Paris 2023",
    "Sticker | Jimpphat (Foil) | Austin 2025",
    "Sticker | Jimpphat (Glitter) | Copenhagen 2024",
    "Sticker | Jimpphat (Holo) | Austin 2025",
    "Sticker | Jimpphat (Holo) | Copenhagen 2024",
    "Sticker | juanflatroo (Glitter) | Paris 2023",
    "Sticker | KOI (Glitter) | Copenhagen 2024",
    "Sticker | KRIMZ (Glitter) | Paris 2023",
    "Sticker | KSCERATO (Foil) | Austin 2025",
    "Sticker | KSCERATO (Glitter) | Antwerp 2022",
    "Sticker | KSCERATO (Glitter) | Copenhagen 2024",
    "Sticker | KSCERATO (Glitter) | Paris 2023",
    "Sticker | KSCERATO (Glitter) | Rio 2022",
    "Sticker | KSCERATO (Holo) | Austin 2025",
    "Sticker | KSCERATO (Holo) | Copenhagen 2024",
    "Sticker | KSCERATO | Berlin 2019",
    "Sticker | KSCERATO | Copenhagen 2024",
    "Sticker | Krad (Glitter) | Paris 2023",
    "Sticker | Kylar (Glitter) | Copenhagen 2024",
    "Sticker | Lake (Foil) | Austin 2025",
    "Sticker | Lake (Holo) | Austin 2025",
    "Sticker | Lake | Austin 2025",
    "Sticker | Legacy (Foil) | Austin 2025",
    "Sticker | Legacy (Glitter) | Copenhagen 2024",
    "Sticker | Legacy (Holo) | Copenhagen 2024",
    "Sticker | Legacy | Austin 2025",
    "Sticker | Lucaozy (Glitter) | Paris 2023",
    "Sticker | Lynn Vision (Foil) | Austin 2025",
    "Sticker | Lynn Vision | Austin 2025",
    "Sticker | M80 (Foil) | Austin 2025",
    "Sticker | M80 | Austin 2025",
    "Sticker | MAJ3R (Glitter) | Copenhagen 2024",
    "Sticker | mezii (Holo) | Austin 2025",
    "Sticker | MIBR (Foil) | Austin 2025",
    "Sticker | MIBR (Glitter) | Antwerp 2022",
    "Sticker | MIBR | Austin 2025",
    "Sticker | MOUZ (Foil) | Austin 2025",
    "Sticker | MOUZ (Glitter) | Copenhagen 2024",
    "Sticker | MOUZ | Austin 2025",
    "Sticker | Magisk (Glitter) | Antwerp 2022",
    "Sticker | Metizport (Foil) | Austin 2025",
    "Sticker | Metizport | Austin 2025",
    "Sticker | Monte (Glitter) | Paris 2023",
    "Sticker | NQZ (Foil) | Austin 2025",
    "Sticker | NQZ (Glitter) | Copenhagen 2024",
    "Sticker | NQZ (Glitter) | Rio 2022",
    "Sticker | NQZ (Gold) | Copenhagen 2024",
    "Sticker | NQZ (Holo) | Copenhagen 2024",
    "Sticker | NQZ | Austin 2025",
    "Sticker | NRG (Foil) | Austin 2025",
    "Sticker | NRG | Austin 2025",
    "Sticker | Natus Vincere (Foil) | Austin 2025",
    "Sticker | Natus Vincere (Glitter) | Copenhagen 2024",
    "Sticker | Natus Vincere (Holo) | Copenhagen 2024",
    "Sticker | Natus Vincere | Austin 2025",
    "Sticker | Nemiga (Foil) | Austin 2025",
    "Sticker | Nemiga | Austin 2025",
    "Sticker | NiKo | Antwerp 2022",
    "Sticker | NiKo | Copenhagen 2024",
    "Sticker | Nodios (Glitter) | Copenhagen 2024",
    "Sticker | Norwi (Glitter) | Antwerp 2022",
    "Sticker | OG (Foil) | Austin 2025",
    "Sticker | OG | Austin 2025",
    "Sticker | Outsiders (Glitter) | Rio 2022",
    "Sticker | Outsiders (Holo) | Rio 2022",
    "Sticker | PGL (Glitter) | Copenhagen 2024",
    "Sticker | Patti (Glitter) | Copenhagen 2024",
    "Sticker | REZ (Glitter) | Antwerp 2022",
    "Sticker | REZ (Glitter) | Rio 2022",
    "Sticker | REZ | Berlin 2019",
    "Sticker | Renegades (Glitter) | Antwerp 2022",
    "Sticker | S1ren | Antwerp 2022",
    "Sticker | SAW (Glitter) | Copenhagen 2024",
    "Sticker | Senzu (Foil) | Austin 2025",
    "Sticker | Senzu (Glitter) | Copenhagen 2024",
    "Sticker | Senzu (Holo) | Copenhagen 2024",
    "Sticker | Senzu | Austin 2025",
    "Sticker | sico (Glitter) | Antwerp 2022",
    "Sticker | Sico (Glitter) | Paris 2023",
    "Sticker | Snappi (Glitter) | Antwerp 2022",
    "Sticker | Snax (Holo) | Shanghai 2024",
    "Sticker | Spinx (Glitter) | Rio 2022",
    "Sticker | Spinx (Holo) | Austin 2025",
    "Sticker | Spinx (Holo) | Copenhagen 2024",
    "Sticker | Starry (Glitter) | Copenhagen 2024",
    "Sticker | Starry | Copenhagen 2024",
    "Sticker | stavn (Glitter) | Antwerp 2022",
    "Sticker | stavn (Glitter) | Paris 2023",
    "Sticker | stavn (Glitter) | Rio 2022",
    "Sticker | SunPayus (Holo) | Paris 2023",
    "Sticker | Swisher (Holo) | Austin 2025",
    "Sticker | TRAVIS (Glitter) | Copenhagen 2024",
    "Sticker | TRAVIS (Holo) | Copenhagen 2024",
    "Sticker | TRY (Glitter) | Rio 2022",
    "Sticker | TYLOO (Foil) | Austin 2025",
    "Sticker | TeSeS (Glitter) | Paris 2023",
    "Sticker | TeSeS (Glitter) | Rio 2022",
    "Sticker | TeSeS (Glitter) | Shanghai 2024",
    "Sticker | Team Liquid (Foil) | Austin 2025",
    "Sticker | Team Liquid (Glitter) | Paris 2023",
    "Sticker | Team Liquid | Austin 2025",
    "Sticker | Team Spirit (Foil) | Austin 2025",
    "Sticker | Team Spirit (Glitter) | Copenhagen 2024",
    "Sticker | Team Spirit | Austin 2025",
    "Sticker | Techno4K (Glitter) | Antwerp 2022",
    "Sticker | Techno4K (Glitter) | Copenhagen 2024",
    "Sticker | Techno4K (Glitter) | Paris 2023",
    "Sticker | Techno4K (Glitter) | Rio 2022",
    "Sticker | Techno4K (Holo) | Copenhagen 2024",
    "Sticker | The MongolZ (Glitter) | Copenhagen 2024",
    "Sticker | The MongolZ (Holo) | Copenhagen 2024",
    "Sticker | The Mongolz (Foil) | Austin 2025",
    "Sticker | The Mongolz | Austin 2025",
    "Sticker | tN1R (Foil) | Austin 2025",
    "Sticker | VINI (Glitter) | Copenhagen 2024",
    "Sticker | vexite | Austin 2025",
    "Sticker | Virtus.Pro (Foil) | Austin 2025",
    "Sticker | Virtus.Pro | Austin 2025",
    "Sticker | Virtus.pro (Glitter) | Copenhagen 2024",
    "Sticker | Vitality (Foil) | Austin 2025",
    "Sticker | Vitality (Glitter) | Antwerp 2022",
    "Sticker | Vitality (Glitter) | Copenhagen 2024",
    "Sticker | Vitality (Glitter) | Paris 2023",
    "Sticker | Vitality | Austin 2025",
    "Sticker | WOOD7 (Glitter) | Paris 2023",
    "Sticker | Wicadia (Foil) | Austin 2025",
    "Sticker | Wicadia (Glitter) | Copenhagen 2024",
    "Sticker | Wicadia (Holo) | Austin 2025",
    "Sticker | Wicadia | Copenhagen 2024",
    "Sticker | Wildcard (Foil) | Austin 2025",
    "Sticker | Wildcard | Austin 2025",
    "Sticker | XANTARES | Antwerp 2022",
    "Sticker | XANTARES | Copenhagen 2024",
    "Sticker | YEKINDAR (Glitter) | Antwerp 2022",
    "Sticker | YEKINDAR (Glitter) | Paris 2023",
    "Sticker | YEKINDAR (Glitter) | Rio 2022",
    "Sticker | YEKINDAR (Holo) | Rio 2022",
    "Sticker | YEKINDAR | Antwerp 2022",
    "Sticker | ZywOo (Glitter) | Antwerp 2022",
    "Sticker | ZywOo (Glitter) | Copenhagen 2024",
    "Sticker | ZywOo (Glitter) | Paris 2023",
    "Sticker | ZywOo (Glitter) | Rio 2022",
    "Sticker | ZywOo (Glitter, Champion) | Paris 2023",
    "Sticker | ZywOo (Holo) | Copenhagen 2024",
    "Sticker | ZywOo | Antwerp 2022",
    "Sticker | ZywOo | Copenhagen 2024",
    "Sticker | ZywOo | Rio 2022",
    "Sticker | adamS (Glitter) | Copenhagen 2024",
    "Sticker | adamS | Copenhagen 2024",
    "Sticker | aliStair (Glitter) | Antwerp 2022",
    "Sticker | apEX (Foil) | Austin 2025",
    "Sticker | apEX (Glitter) | Copenhagen 2024",
    "Sticker | apEX (Glitter) | Shanghai 2024",
    "Sticker | apEX (Holo) | Copenhagen 2024",
    "Sticker | arT (Glitter) | Copenhagen 2024",
    "Sticker | arT (Glitter) | Paris 2023",
    "Sticker | arT | Austin 2025",
    "Sticker | arT | Copenhagen 2024",
    "Sticker | arrozdoce | Copenhagen 2024",
    "Sticker | b1t (Glitter) | Antwerp 2022",
    "Sticker | b1t (Glitter) | Copenhagen 2024",
    "Sticker | b1t (Glitter) | Paris 2023",
    "Sticker | b1t (Glitter) | Rio 2022",
    "Sticker | b1t (Glitter) | Shanghai 2024",
    "Sticker | b1t (Glitter, Champion) | Copenhagen 2024",
    "Sticker | b1t (Holo) | Stockholm 2021",
    "Sticker | bLitz (Foil) | Austin 2025",
    "Sticker | bLitz (Glitter) | Antwerp 2022",
    "Sticker | bLitz (Glitter) | Copenhagen 2024",
    "Sticker | bLitz (Glitter) | Rio 2022",
    "Sticker | biguzera (Glitter) | Copenhagen 2024",
    "Sticker | biguzera (Glitter) | Shanghai 2024",
    "Sticker | biguzera (Holo) | Copenhagen 2024",
    "Sticker | biguzera (Holo) | Shanghai 2024",
    "Sticker | bodyy | Shanghai 2024",
    "Sticker | br0 (Foil) | Austin 2025",
    "Sticker | br0 | Austin 2025",
    "Sticker | brnz4n (Foil) | Austin 2025",
    "Sticker | brnz4n (Holo) | Austin 2025",
    "Sticker | broky (Glitter) | Copenhagen 2024",
    "Sticker | broky (Glitter) | Paris 2023",
    "Sticker | broky (Glitter, Champion) | Antwerp 2022",
    "Sticker | cadiaN | Antwerp 2022",
    "Sticker | chelo (Glitter) | Antwerp 2022",
    "Sticker | coldzera (Glitter) | Copenhagen 2024",
    "Sticker | coldzera (Holo) | Copenhagen 2024",
    "Sticker | dav1d (Glitter) | Antwerp 2022",
    "Sticker | dav1d | Antwerp 2022",
    "Sticker | dav1deuS | Austin 2025",
    "Sticker | decenty (Glitter) | Copenhagen 2024",
    "Sticker | decenty (Gold) | Copenhagen 2024",
    "Sticker | decenty (Holo) | Copenhagen 2024",
    "Sticker | degster (Glitter) | Antwerp 2022",
    "Sticker | dgt (Foil) | Austin 2025",
    "Sticker | dgt (Glitter) | Rio 2022",
    "Sticker | dgt | Austin 2025",
    "Sticker | donk (Glitter) | Copenhagen 2024",
    "Sticker | donk (Glitter) | Shanghai 2024",
    "Sticker | donk (Glitter, Champion) | Shanghai 2024",
    "Sticker | donk (Holo, Champion) | Shanghai 2024",
    "Sticker | donk | Copenhagen 2024",
    "Sticker | drop (Glitter) | Rio 2022",
    "Sticker | dumau (Glitter) | Copenhagen 2024",
    "Sticker | dumau (Glitter) | Rio 2022",
    "Sticker | dumau (Gold) | Copenhagen 2024",
    "Sticker | dumau (Holo) | Copenhagen 2024",
    "Sticker | dupreeh (Glitter) | Antwerp 2022",
    "Sticker | dupreeh (Glitter) | Paris 2023",
    "Sticker | dupreeh (Glitter) | Rio 2022",
    "Sticker | electronic (Glitter) | Paris 2023",
    "Sticker | exit | Austin 2025",
    "Sticker | fEAR (Glitter) | Shanghai 2024",
    "Sticker | FalleN (Glitter) | Antwerp 2022",
    "Sticker | FalleN (Glitter) | Copenhagen 2024",
    "Sticker | FalleN (Holo) | Austin 2025",
    "Sticker | FalleN | Antwerp 2022",
    "Sticker | FalleN | Copenhagen 2024",
    "Sticker | FalleN | Shanghai 2024",
    "Sticker | fame (Glitter) | Copenhagen 2024",
    "Sticker | faveN (Glitter) | Antwerp 2022",
    "Sticker | forZe eSports (Glitter) | Antwerp 2022",
    "Sticker | forZe eSports (Glitter) | Paris 2023",
    "Sticker | frozen (Glitter) | Copenhagen 2024",
    "Sticker | frozen (Glitter) | Paris 2023",
    "Sticker | frozen (Glitter) | Rio 2022",
    "Sticker | frozen (Glitter) | Shanghai 2024",
    "Sticker | gla1ve (Glitter) | Antwerp 2022",
    "Sticker | gla1ve (Glitter) | Copenhagen 2024",
    "Sticker | gxx- (Glitter) | Antwerp 2022",
    "Sticker | gxx- (Glitter) | Paris 2023",
    "Sticker | hades (Foil) | Austin 2025",
    "Sticker | hades (Glitter) | Copenhagen 2024",
    "Sticker | hades (Holo) | Austin 2025",
    "Sticker | hades | Austin 2025",
    "Sticker | hallzerk (Glitter) | Copenhagen 2024",
    "Sticker | headtr1ck (Glitter) | Paris 2023",
    "Sticker | headtr1ck (Gold) | Paris 2023",
    "Sticker | headtr1ck (Holo) | Austin 2025",
    "Sticker | headtr1ck (Holo) | Paris 2023",
    "Sticker | huNter- (Foil) | Austin 2025",
    "Sticker | huNter- | Berlin 2019",
    "Sticker | huNter- (Glitter) | Copenhagen 2024",
    "Sticker | huNter- (Glitter) | Paris 2023",
    "Sticker | huNter- (Holo) | Austin 2025",
    "Sticker | iM (Glitter) | Copenhagen 2024",
    "Sticker | iM (Glitter) | Paris 2023",
    "Sticker | iM (Glitter) | Shanghai 2024",
    "Sticker | iM (Glitter, Champion) | Copenhagen 2024",
    "Sticker | iM | Austin 2025",
    "Sticker | insani (Foil) | Austin 2025",
    "Sticker | insani (Glitter) | Shanghai 2024",
    "Sticker | insani (Gold) | Shanghai 2024",
    "Sticker | insani (Holo) | Austin 2025",
    "Sticker | insani (Holo) | Shanghai 2024",
    "Sticker | insani | Austin 2025",
    "Sticker | isak (Foil) | Austin 2025",
    "Sticker | isak | Austin 2025",
    "Sticker | jL (Glitter) | Copenhagen 2024",
    "Sticker | jL (Glitter, Champion) | Copenhagen 2024",
    "Sticker | jabbi (Glitter) | Antwerp 2022",
    "Sticker | jabbi (Glitter) | Rio 2022",
    "Sticker | jabbi | Antwerp 2022",
    "Sticker | jambo (Glitter) | Shanghai 2024",
    "Sticker | Jee | Copenhagen 2024",
    "Sticker | jeorge (Foil) | Austin 2025",
    "Sticker | jeorge | Austin 2025",
    "Sticker | k0nfig (Glitter) | Antwerp 2022",
    "Sticker | karrigan (Glitter) | Copenhagen 2024",
    "Sticker | karrigan (Glitter) | Paris 2023",
    "Sticker | karrigan (Glitter, Champion) | Antwerp 2022",
    "Sticker | khaN | Austin 2025",
    "Sticker | kraghen (Glitter) | Copenhagen 2024",
    "Sticker | kyxsan | Copenhagen 2024",
    "Sticker | latto (Foil) | Austin 2025",
    "Sticker | latto (Glitter) | Copenhagen 2024",
    "Sticker | latto (Glitter) | Rio 2022",
    "Sticker | latto (Gold) | Copenhagen 2024",
    "Sticker | latto (Holo) | Copenhagen 2024",
    "Sticker | latto | Austin 2025",
    "Sticker | lux (Glitter) | Copenhagen 2024",
    "Sticker | lux | Austin 2025",
    "Sticker | m0NESY (Glitter) | Copenhagen 2024",
    "Sticker | m0NESY (Holo) | Copenhagen 2024",
    "Sticker | magixx (Glitter) | Antwerp 2022",
    "Sticker | magixx (Glitter) | Copenhagen 2024",
    "Sticker | magixx (Glitter, Champion) | Shanghai 2024",
    "Sticker | magixx (Holo, Champion) | Shanghai 2024",
    "Sticker | magixx | Austin 2025",
    "Sticker | malbsMd (Foil) | Austin 2025",
    "Sticker | malbsMd (Glitter) | Shanghai 2024",
    "Sticker | malbsMd (Gold) | Austin 2025",
    "Sticker | malbsMd (Holo) | Austin 2025",
    "Sticker | malbsMd (Holo) | Shanghai 2024",
    "Sticker | mezii (Holo) | Copenhagen 2024",
    "Sticker | molodoy (Foil) | Austin 2025",
    "Sticker | molodoy (Holo) | Austin 2025",
    "Sticker | mzinho (Foil) | Austin 2025",
    "Sticker | mzinho (Glitter) | Copenhagen 2024",
    "Sticker | mzinho (Holo) | Austin 2025",
    "Sticker | mzinho (Holo) | Copenhagen 2024",
    "Sticker | n0rb3r7 (Glitter) | Copenhagen 2024",
    "Sticker | n1ssim (Glitter) | Copenhagen 2024",
    "Sticker | n1ssim (Holo) | Copenhagen 2024",
    "Sticker | n1ssim | Austin 2025",
    "Sticker | nexa (Glitter) | Rio 2022",
    "Sticker | nicoodoz (Glitter) | Antwerp 2022",
    "Sticker | nicoodoz (Glitter) | Rio 2022",
    "Sticker | nitr0 (Glitter) | Paris 2023",
    "Sticker | nitr0 (Glitter) | Rio 2022",
    "Sticker | noway (Glitter) | Copenhagen 2024",
    "Sticker | noway (Holo) | Copenhagen 2024",
    "Sticker | npl (Holo) | Paris 2023",
    "Sticker | oSee | Austin 2025",
    "Sticker | paiN Gaming (Foil) | Austin 2025",
    "Sticker | paiN Gaming (Glitter) | Copenhagen 2024",
    "Sticker | paiN Gaming | Austin 2025",
    "Sticker | rain (Glitter) | Copenhagen 2024",
    "Sticker | rain (Glitter, Champion) | Antwerp 2022",
    "Sticker | rain | Antwerp 2022",
    "Sticker | rain | Copenhagen 2024",
    "Sticker | refrezh (Glitter) | Antwerp 2022",
    "Sticker | rigoN (Glitter) | Antwerp 2022",
    "Sticker | ropz (Champion) | Antwerp 2022",
    "Sticker | ropz (Champion) | Austin 2025",
    "Sticker | ropz (Glitter) | Rio 2022",
    "Sticker | ropz (Glitter, Champion) | Antwerp 2022",
    "Sticker | ropz | Copenhagen 2024",
    "Sticker | s1mple (Glitter) | Antwerp 2022",
    "Sticker | s1mple (Glitter) | Paris 2023",
    "Sticker | s1mple (Holo) | Stockholm 2021",
    "Sticker | s1mple | Antwerp 2022",
    "Sticker | s1mple | Stockholm 2021",
    "Sticker | saadzin (Foil) | Austin 2025",
    "Sticker | saadzin (Holo) | Austin 2025",
    "Sticker | saadzin | Austin 2025",
    "Sticker | saffee | Austin 2025",
    "Sticker | salazar (Glitter) | Copenhagen 2024",
    "Sticker | salazar (Holo) | Copenhagen 2024",
    "Sticker | sdy (Glitter) | Paris 2023",
    "Sticker | sense | Copenhagen 2024",
    "Sticker | sh1ro (Foil) | Austin 2025",
    "Sticker | sh1ro (Glitter) | Copenhagen 2024",
    "Sticker | sh1ro (Glitter) | Shanghai 2024",
    "Sticker | sh1ro (Glitter, Champion) | Shanghai 2024",
    "Sticker | sh1ro (Holo) | Copenhagen 2024",
    "Sticker | sh1ro (Holo, Champion) | Shanghai 2024",
    "Sticker | sh1ro | Antwerp 2022",
    "Sticker | sh1ro | Stockholm 2021",
    "Sticker | sico (Holo) | Antwerp 2022",
    "Sticker | sico | Antwerp 2022",
    "Sticker | siuhy (Glitter) | Paris 2023",
    "Sticker | siuhy (Glitter) | Rio 2022",
    "Sticker | sk0R (Glitter) | Paris 2023",
    "Sticker | skullz (Foil) | Austin 2025",
    "Sticker | skullz (Glitter) | Shanghai 2024",
    "Sticker | skullz (Holo) | Paris 2023",
    "Sticker | snow (Foil) | Austin 2025",
    "Sticker | snow (Glitter) | Shanghai 2024",
    "Sticker | snow (Holo) | Austin 2025",
    "Sticker | snow (Holo) | Shanghai 2024",
    "Sticker | stavn (Holo) | Stockholm 2021",
    "Sticker | story | Copenhagen 2024",
    "Sticker | susp (Foil) | Austin 2025",
    "Sticker | susp (Glitter) | Shanghai 2024",
    "Sticker | susp | Austin 2025",
    "Sticker | torzsi (Glitter) | Copenhagen 2024",
    "Sticker | torzsi (Glitter) | Rio 2022",
    "Sticker | torzsi (Gold) | Copenhagen 2024",
    "Sticker | torzsi (Holo) | Austin 2025",
    "Sticker | torzsi (Holo) | Copenhagen 2024",
    "Sticker | vexite (Foil) | Austin 2025",
    "Sticker | vexite (Glitter) | Rio 2022",
    "Sticker | vexite (Glitter) | Shanghai 2024",
    "Sticker | w0nderful (Foil) | Austin 2025",
    "Sticker | w0nderful (Glitter) | Copenhagen 2024",
    "Sticker | w0nderful (Glitter) | Shanghai 2024",
    "Sticker | w0nderful (Holo) | Austin 2025",
    "Sticker | westmelon (Glitter) | Copenhagen 2024",
    "Sticker | woxic (Holo) | Austin 2025",
    "Sticker | woxic | Antwerp 2022",
    "Sticker | woxic | Copenhagen 2024",
    "Sticker | xertioN (Foil) | Austin 2025",
    "Sticker | xertioN (Glitter) | Copenhagen 2024",
    "Sticker | xertioN (Glitter) | Rio 2022",
    "Sticker | xertioN (Holo) | Austin 2025",
    "Sticker | xertioN (Holo) | Copenhagen 2024",
    "Sticker | yuurih (Foil) | Austin 2025",
    "Sticker | yuurih (Glitter) | Copenhagen 2024",
    "Sticker | yuurih (Glitter) | Rio 2022",
    "Sticker | yuurih (Glitter) | Shanghai 2024",
    "Sticker | yuurih (Gold) | Paris 2023",
    "Sticker | yuurih (Holo) | Austin 2025",
    "Sticker | yuurih (Holo) | Copenhagen 2024",
    "Sticker | yuurih | Copenhagen 2024",
    "Sticker | zont1x (Foil) | Austin 2025",
    "Sticker | zont1x (Glitter) | Copenhagen 2024",
    "Sticker | zont1x (Glitter) | Shanghai 2024",
    "Sticker | zont1x (Holo, Champion) | Shanghai 2024",
    "Sticker | zweih (Foil) | Austin 2025",
    "Souvenir R8 Revolver | Inlay (Minimal Wear)",
    "Souvenir R8 Revolver | Inlay (Factory New)",
    "Souvenir AUG | Snake Pit (Minimal Wear)",
    "Souvenir MP7 | Sunbaked (Minimal Wear)",
    "Souvenir MP7 | Sunbaked (Factory New)",
    "XM1014 | Hieroglyph (Factory New)",
    "Souvenir XM1014 | Hieroglyph (Minimal Wear)",
    "TEC-9 | Rebel (Minimal Wear)",
    "R8 Revolver | Banana Cannon (Minimal Wear)",
    "StatTrak™ R8 Revolver | Grip (Minimal Wear)",
    "R8 Revolver | Grip (Minimal Wear)",
    "R8 Revolver | Junk Yard (Minimal Wear)",
    "R8 Revolver | Survivalist (Minimal Wear)",
    "SG 553 | Cyberforce (Minimal Wear)",
    "SSG 08 | Memorial (Factory New)",
    "P90 | Traction (Minimal Wear)",
    "FAMAS | Meow 36 (Minimal Wear)",
    "Souvenir CZ75-Auto | Silver (Factory New)",
    "Souvenir Five-SeveN | Withered Vine (Factory New)",
    "Souvenir Nova | Rain Station (Minimal Wear)",
    "Souvenir P2000 | Panther Camo (Factory New)",
    "Souvenir UMP-45 | Mechanism (Minimal Wear)",
    "Souvenir USP-S | Desert Tactical (Minimal Wear)",
    "Souvenir P250 | Facility Draft (Factory New)",
    "M4A1-S | Mud-Spec (Minimal Wear)",
    "Negev | Wall Bang (Factory New)",
    "Sticker | broky (Holo, Champion) | Antwerp 2022",
    "Sticker | mezii (Glitter) | Copenhagen 2024",
    "Sticker | Spinx (Glitter) | Copenhagen 2024"
]

















