name: Run monitor.py

on: workflow_dispatch

jobs:
  run-monitor:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'  # Você pode ajustar para a versão que usa

      - name: Install dependencies
        run: |
          pip install -r requirements.txt || true

      - name: Run monitor.py
        run: python monitor_de_stickers/monitor.py
        working-directory: sticker-monitor
