name: Run main.py

on: workflow_dispatch

jobs:
  run-main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'  # Ou a versão que seu projeto usa

      - name: Install dependencies
        run: |
          pip install -r requirements.txt || true
      - name: Run main.py
        run: python main.py
